language: node_js
node_js:
  - "12"
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  app: tfjs-what-is-this
  api_key: j6sJUVBU9Y+dGSh56sIZlo2yZ7pA8vk/GQUBEAiBPZXyc/WahP+Tsdz4iMYOT0+QSD1j+ob3t9L0WkT14vvxfbhlG894wuxIAjGT5LLOsnkV7DlDDfgDOzPCSJ2fERaCAAyNv6jKyZh3KMsoin53yTUqIuGsuFm0yW6DlRkJ4bumL2hbeGZ/kKSsg/Jpj9TufmOhK5oMINVokj8gMUXQePCFxD5IbIGX2kPW20o+ElH7C0xxJbaxKJpYuPTs1f6wLB6GdJ6xT+5DN6v0fjcBuMpogV5lVkoA1IOEwL8Z0e6Un44hkz+q0BCR2uZBIZHvQE7FfTBKQHPlA4wJXvUmbNrB8wMCiE7F7tp1RS6yygEYbJ8pPcYX5Wu9L0qjlvGMKvK9GCP0RB60Is2tmfY71ab4QU68WvqfHT3ANzntYM3EvuXdDYYROTEgWm2B6gtJHNgWJ87+nxs43fuqY3irAA+LhQslugdd0/DrdOJmq6ymmWmtnF/PZWsUtb39NpJJYHozBwgVc49xtX8LlNH7A8ZhM4dspRfKW+CMFJG3C2mHmpT3tRZBYAacR2Ny5dAgWMxjIit5p6hzoEVYT4qN/8nD7U0KWbkbVJZFfybPVW0sc+6e1TF+pjVCz8gIkdE0n1C9SRvmA2uaCe6bCcIg7hKkpMXBU/17BDretE8XPwg=
