language: node_js
node_js:
  - "12"
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  app: tfjs-what-is-this.herokuapp.com
  api_key:
    secure: PKBJpZQBGD8nZ8G6kc3DFwtj5I4W0cRywffBb1GJdW+a4gW5UZbuxRdb7gqbI8zCpSVj2HfozRksa2Gnt4zYvUT2qF1AHtI1EEf4oy1RQKD4Sfj2lEPNTlXu0K2vUozZ6Ow75vjI1vdHr8gGAj2Z/6aqcpEfOpzzGbEoVltApYuu0pjfJdUF9ITtAE1mrs8DWYulfSmT5lcGBhqKYlQHEbo6VSZJa9dAgMOr7vBkgkRyEvsM0wSai8cVA7oMn0OXI5FcaScGONYVYmv0SN46E9ByEr6t5krvl6gwEt9eF3s77MCb6tNu8KjNXHXcuJYWXyJEMx1Df0v01wMICe3a65+MtSXcgwMOC6B/H0VLoNRsEgCgLuAvzhyd0BSSjwefhxhHQH56IZcf1wyZntADlPEgENiCasopZUY5mY2E4Z2VqbySqsnNNbHTZpICyE5C7DlGamNz4NRsHJaeiyXRYdfWubseU4yEPNYTyTFj+pCKdarL6INRiGNJvz7NBqY5lM83gAm6pYC3VzOkC1HZF6cvAkb0PO2WJ+VnUnzI40/Ts2Q60kLp4B/Zm36b5eJnSejak8oipPi5po3Fak5qMuTJrr4wcVFXeWQEV5feL/oiH3XuWFISAHnNDpJGtFPVzNxpGFPunhE2da2QjeZ9qissF2aMYjP0Lr4qXpjU4nM=
